//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Model.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_Header
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice_Header()
        {
            this.Invoice_Details = new HashSet<Invoice_Details>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public Nullable<int> Payment_Method_Id { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<double> DiscountPercentage { get; set; }
        public Nullable<decimal> NetTotal { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_Details> Invoice_Details { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
    }
}
