//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Model.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_Details
    {
        public int Id { get; set; }
        public Nullable<int> Invoice_Header_Id { get; set; }
        public Nullable<int> Item_Id { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual Invoice_Header Invoice_Header { get; set; }
        public virtual Item Item { get; set; }
    }
}
